version: '3.4'
services:
  course-midtier:
    build:
      context: .
      args:
        SERVICE_PORT: ${SERVICE_PORT}
    image: "${DOCKER_REGISTRY}wikitolearn/course-midtier:${DOCKER_IMAGE_COURSE_MIDTIER_TAG}"
    environment:
      KEYCLOAK_URI: ${KEYCLOAK_URI}
      KEYCLOAK_AUTH_REALM: ${KEYCLOAK_AUTH_REALM}
      COURSES_BACKEND_URI: ${COURSES_BACKEND_URI}
      CHAPTERS_BACKEND_URI: ${CHAPTERS_BACKEND_URI}
      PAGES_BACKEND_URI: ${PAGES_BACKEND_URI}
      SERVICE_PORT: ${SERVICE_PORT}
      SSL_ENABLED: ${SSL_ENABLED}
      MTLS_STATUS: ${MTLS_STATUS}
    ports:
      - ${SERVICE_PORT}:${SERVICE_PORT}