# Spring properties
spring:
  application:
    name: CourseMidTier
  output:
    ansi:
      enabled: DETECT

# Management properties
management:
  endpoints:
    web:
      base-path: /_meta
      path-mapping:
        health: status
      exposure:
        include: health,info,metrics
  health:
    defaults:
      enabled: false

# Security properties
security:
  oauth2:
    resource:
      user-info-uri: ${KEYCLOAK_URI}/auth/realms/${KEYCLOAK_AUTH_REALM}/protocol/openid-connect/userinfo
      token-info-uri: ${KEYCLOAK_URI}/auth/realms/${KEYCLOAK_AUTH_REALM}/protocol/openid-connect/token/introspect
      prefer-token-info: false
      jwk:
        key-set-uri: ${KEYCLOAK_URI}/auth/realms/${KEYCLOAK_AUTH_REALM}/protocol/openid-connect/certs

# Springfox properties    
springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs

# Logging properties
logging:
  pattern:
    file: '%d{"yyyy-MM-dd HH:mm:ss,SSS"} %-5level [%c] \(%thread\) : %msg%n'
    console: '%d{"yyyy-MM-dd HH:mm:ss,SSS"} %-5level [%c] \(%thread\) : %msg%n'

# Server properties
server:
  port: ${SERVICE_PORT}
  ssl:
    enabled: ${SSL_ENABLED}
    key-store: file:./app-keystore.jks
    key-store-password: changeme
    key-password: changeme
    trust-store: file:./app-truststore.jks
    trust-store-password: changeme
    client-auth: ${MTLS_STATUS}

# Application properties
application:
  clients:
    courses-backend: ${COURSES_BACKEND_URI}/v1
    chapters-backend: ${CHAPTERS_BACKEND_URI}/v1
    pages-backend: ${PAGES_BACKEND_URI}/v1
